version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1 # Use a specific version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity in development
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1 # Use the same version as Elasticsearch
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Connects to the Elasticsearch service name
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

volumes:
  esdata:

networks:
  elastic-net:
    driver: bridge